return {
	['Trippi Troppi'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://127209942671314",
			['Candy'] = "rbxassetid://94310818365889",
			['Vulcanic'] = "rbxassetid://119284754986881",
			['Radioactive'] = "rbxassetid://84116760780985"
		}
	},
	['Trulimero Trulichina'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://90927105824745",
			['Candy'] = "rbxassetid://102014188160177",
			['Vulcanic'] = "rbxassetid://105218830513054",
			['Radioactive'] = "rbxassetid://125707636039138"
		}
	},
	['Lirili Larila'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://122007997716751",
			['Candy'] = "rbxassetid://776434744483993",
			['Vulcanic'] = "rbxassetid://78512178555026",
			['Radioactive'] = "rbxassetid://113563296454646"
		}
	},
	['Brr Patapim'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://129615662721769",
			['Candy'] = "rbxassetid://135192159581632",
			['Vulcanic'] = "rbxassetid://125159143028682",
			['Radioactive'] = "rbxassetid://100808927897124"
		}
	},
	['Tung Tung Sahur'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://119183012909863",
			['Candy'] = "rbxassetid://99483661603024",
			['Vulcanic'] = "rbxassetid://110368024183766",
			['Radioactive'] = "rbxassetid://138786643568559"
		}
	},
	['Svinino Bombondino'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://119356877241061",
			['Candy'] = "rbxassetid://119356877241061",
			['Vulcanic'] = "rbxassetid://98870008327958",
			['Radioactive'] = "rbxassetid://109792847311335"
		}
	},
	['Ta Ta Ta Sahur'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://70566109591422",
			['Candy'] = "rbxassetid://97389144497844",
			['Vulcanic'] = "rbxassetid://124617055017051",
			['Radioactive'] = "rbxassetid://114948580467315"
		}
	},
	['Bananita Dolfinita'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://98559334828685",
			['Candy'] = "rbxassetid://79613212620905",
			['Vulcanic'] = "rbxassetid://127225083437639",
			['Radioactive'] = "rbxassetid://72490158836175"
		}
	},
	['Frulli Frulla'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://119385412383230",
			['Candy'] = "rbxassetid://125138999200577",
			['Vulcanic'] = "rbxassetid://83510188122234",
			['Radioactive'] = "rbxassetid://134903164761315"
		}
	},
	['Capuccino Assassino'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://72721100950294",
			['Candy'] = "rbxassetid://88399380143071",
			['Vulcanic'] = "rbxassetid://99436925434766",
			['Radioactive'] = "rbxassetid://77062441001790"
		}
	},
	['Rhino Toasterino'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://135272197125067",
			['Candy'] = "rbxassetid://84781687100412",
			['Vulcanic'] = "rbxassetid://117325347623812",
			['Radioactive'] = "rbxassetid://105980737187360"
		}
	},
	['Pipi Avocado'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://133865313821236",
			['Candy'] = "rbxassetid://78402806583426",
			['Vulcanic'] = "rbxassetid://81387112890704",
			['Radioactive'] = "rbxassetid://107021938802391"
		}
	},
	['Gangster Footera'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://81773767765555",
			['Candy'] = "rbxassetid://101397779919902",
			['Vulcanic'] = "rbxassetid://81943260150182",
			['Radioactive'] = "rbxassetid://100488772951685"
		}
	},
	['Cacto Hipopotamo'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://107410508315087",
			['Candy'] = "rbxassetid://137958314852407",
			['Vulcanic'] = "rbxassetid://120562547561673",
			['Radioactive'] = "rbxassetid://101117847390119"
		}
	},
	['Bombardino Crocodilo'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://87725596433588",
			['Candy'] = "rbxassetid://79103766779633",
			['Vulcanic'] = "rbxassetid://82558873562727",
			['Radioactive'] = "rbxassetid://99547903597364"
		}
	},
	['Bombardini Gusini'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://96094515630572",
			['Candy'] = "rbxassetid://126273757591874",
			['Vulcanic'] = "rbxassetid://106622136159319",
			['Radioactive'] = "rbxassetid://92009034782928"
		}
	},
	['Salamino Pinguino'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://89438654783457",
			['Candy'] = "rbxassetid://86472155830040",
			['Vulcanic'] = "rbxassetid://78759661942564",
			['Radioactive'] = "rbxassetid://116620280328523"
		}
	},
	['Ballerina Capuccina'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://112777457445674",
			['Candy'] = "rbxassetid://133944471233550",
			['Vulcanic'] = "rbxassetid://79846110722416",
			['Radioactive'] = "rbxassetid://84376841032478"
		}
	},
	['Chimpanzini Bananini'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://109762416653356",
			['Candy'] = "rbxassetid://70703699907923",
			['Vulcanic'] = "rbxassetid://117096055200666",
			['Radioactive'] = "rbxassetid://132134657539293"
		}
	},
	['Glorbo Fruttodrillo'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://99520700384181",
			['Candy'] = "rbxassetid://135970556309858",
			['Vulcanic'] = "rbxassetid://95146064600036",
			['Radioactive'] = "rbxassetid://135609416833948"
		}
	},
	['Boneca Ambalabu'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://70677258806106",
			['Candy'] = "rbxassetid://74724763084131",
			['Vulcanic'] = "rbxassetid://117101075138923",
			['Radioactive'] = "rbxassetid://137610520220083"
		}
	},
	['Espressona Signora'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://122981480711143",
			['Candy'] = "rbxassetid://74803062484353",
			['Vulcanic'] = "rbxassetid://70477417838674",
			['Radioactive'] = "rbxassetid://132793592719353"
		}
	},
	['Frigo Camelo'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://92706519801219",
			['Candy'] = "rbxassetid://124823962325520",
			['Vulcanic'] = "rbxassetid://115359566189093",
			['Radioactive'] = "rbxassetid://87071002992378"
		}
	},
	['Garama And Madundung'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://86583259268073",
			['Candy'] = "rbxassetid://100144346958899",
			['Vulcanic'] = "rbxassetid://139240361872817",
			['Radioactive'] = "rbxassetid://89886579983104"
		}
	},
	['Strawberry Flamingelli'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://104061465642659",
			['Candy'] = "rbxassetid://93665590405146",
			['Vulcanic'] = "rbxassetid://123541664004924",
			['Radioactive'] = "rbxassetid://91711154598631"
		}
	},
	['Tralalero Tralala'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://91651340501942",
			['Candy'] = "rbxassetid://112443545382479",
			['Vulcanic'] = "rbxassetid://82322582918834",
			['Radioactive'] = "rbxassetid://114948580467315"
		}
	},
	['Orcalero Orcala'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://80587245167983",
			['Candy'] = "rbxassetid://80521710152881",
			['Vulcanic'] = "rbxassetid://127297739928675",
			['Radioactive'] = "rbxassetid://127962689523318"
		}
	},
	['Odin Din Din Dun'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://118144852065262",
			['Candy'] = "rbxassetid://134271504797705",
			['Vulcanic'] = "rbxassetid://71408944417983",
			['Radioactive'] = "rbxassetid://124957618857395"
		}
	},
	['Vaca Saturno Saturnita'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://105053266092995",
			['Candy'] = "rbxassetid://109935058289850",
			['Vulcanic'] = "rbxassetid://134417363500971",
			['Radioactive'] = "rbxassetid://125334982549134"
		}
	},
	['Los Tralaleritos'] = {
		['ImageId'] = {
			['Normal'] = "rbxassetid://94369313035750",
			['Candy'] = "rbxassetid://114102612056433",
			['Vulcanic'] = "rbxassetid://133136224520514",
			['Radioactive'] = "rbxassetid://127052462229794"
		}
	},
}