local module = {

	[1] = {
		RewardType = "Cash",
		Amount = 500
	},

	[2] = {
		RewardType = "Cash",
		Amount = 2500
	},

	[3] = {

		RewardType = "Cash",
		Amount = 5000
	},

	[4] = {

		RewardType = "Cash",
		Amount = 12500
	},

	[5] = {
		RewardType = "Cash",
		Amount = 25000
	},

	[6] = {

		RewardType = "Cash",
		Amount = 75000
	},

	[7] = {

		RewardType = "Chair",
		Amount = 1,
		Name = "Throne"
	},
}

module.DailyTimer = 86400

return module
