local module = {

	[1] = {
		RewardType = "Cash",
		Amount = 350,
		TimeReq = 30
	},

	[2] = {
		RewardType = "Cash",
		Amount = 700,
		TimeReq = 1 * 60
	},

	[3] = {
		RewardType = "Cash",
		Amount = 1000,
		TimeReq = 2 * 60
	},

	[4] = {
		RewardType = "OPRoll",
		Amount = 1,
		TimeReq = 5 * 60
	},

	[5] = {
		RewardType = "Cash",
		Amount = 8000,
		TimeReq = 8 * 60
	},

	[6] = {
		RewardType = "Cash",
		Amount = 12000,
		TimeReq = 10 * 60
	},
	
	[7] = {
		RewardType = "Cash",
		Amount = 25000,
		TimeReq = 15 * 60
	},
	
	[8] = {
		RewardType = "Chair",
		ChairName = "Invisible",
		TimeReq = 20 * 60
	},
	
	[9] = {
		RewardType = "Cash",
		Amount = 100000,
		TimeReq = 25 * 60
	},
	
	[10] = {
		RewardType = "SuperRoll",
		Amount = 1,
		TimeReq = 30 * 60
	},
	
	[11] = {
		RewardType = "Cash",
		Amount = 250000,
		TimeReq = 45 * 60
	},
	
	[12] = {
		RewardType = "Chair",
		ChairName = "Gamer",
		TimeReq = 60 * 60
	},
	
	
}



return module
